/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DeleteRequest {
  'status' : RequestStatus,
  'owner' : Principal,
  'listingId' : bigint,
  'createdAt' : Time,
  'rejectionReason' : [] | [string],
  'reviewedAt' : [] | [Time],
}
export interface EditRequest {
  'status' : RequestStatus,
  'owner' : Principal,
  'listingId' : bigint,
  'createdAt' : Time,
  'rejectionReason' : [] | [string],
  'reviewedAt' : [] | [Time],
  'editedListing' : Listing,
}
export type ExternalBlob = Uint8Array;
export type Facility = { 'wifi' : null } |
  { 'sharedBathroom' : null } |
  { 'furniture' : null } |
  { 'parking' : null } |
  { 'airConditioning' : null } |
  { 'laundry' : null };
export interface Listing {
  'id' : bigint,
  'status' : ListingStatus,
  'title' : string,
  'propertyType' : PropertyType,
  'owner' : Principal,
  'createdAt' : Time,
  'description' : string,
  'rentalDurations' : Array<RentalDuration>,
  'priceRupiah' : bigint,
  'updatedAt' : Time,
  'facilities' : Array<Facility>,
  'location' : string,
  'photos' : Array<ExternalBlob>,
}
export interface ListingInput {
  'title' : string,
  'propertyType' : PropertyType,
  'description' : string,
  'rentalDurations' : Array<RentalDuration>,
  'priceRupiah' : bigint,
  'facilities' : Array<Facility>,
  'location' : string,
  'photos' : Array<ExternalBlob>,
}
export type ListingStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : string };
export type PropertyType = { 'kos' : null } |
  { 'kontrakan' : null };
export type RentalDuration = { 'monthly' : null } |
  { 'yearly' : null } |
  { 'daily' : null };
export type RequestStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : string };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveListing' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'countListingsByPropertyType' : ActorMethod<[], [bigint, bigint]>,
  'createListing' : ActorMethod<[ListingInput], bigint>,
  'filterListingsByLocation' : ActorMethod<[string], Array<Listing>>,
  'filterListingsByPriceRange' : ActorMethod<[bigint, bigint], Array<Listing>>,
  'getAllDeleteRequests' : ActorMethod<[], Array<DeleteRequest>>,
  'getAllEditRequests' : ActorMethod<[], Array<EditRequest>>,
  'getAllListings' : ActorMethod<[], Array<Listing>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getListing' : ActorMethod<[bigint], Listing>,
  'getListingFacilities' : ActorMethod<[bigint], Array<Facility>>,
  'getListingLocations' : ActorMethod<[], Array<string>>,
  'getListingPhotos' : ActorMethod<[bigint], Array<ExternalBlob>>,
  'getListingStatus' : ActorMethod<[bigint], ListingStatus>,
  'getListingsByOwner' : ActorMethod<[Principal], Array<Listing>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'processDeleteRequest' : ActorMethod<
    [bigint, boolean, [] | [string]],
    undefined
  >,
  'processEditRequest' : ActorMethod<
    [bigint, boolean, [] | [string]],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchListingsByTitle' : ActorMethod<[string], Array<Listing>>,
  'submitDeleteRequest' : ActorMethod<[bigint], undefined>,
  'submitEditRequest' : ActorMethod<[bigint, Listing], undefined>,
  'uploadPhoto' : ActorMethod<[bigint, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];