/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PropertyType = IDL.Variant({
  'kos' : IDL.Null,
  'kontrakan' : IDL.Null,
});
export const RentalDuration = IDL.Variant({
  'monthly' : IDL.Null,
  'yearly' : IDL.Null,
  'daily' : IDL.Null,
});
export const Facility = IDL.Variant({
  'wifi' : IDL.Null,
  'sharedBathroom' : IDL.Null,
  'furniture' : IDL.Null,
  'parking' : IDL.Null,
  'airConditioning' : IDL.Null,
  'laundry' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ListingInput = IDL.Record({
  'title' : IDL.Text,
  'propertyType' : PropertyType,
  'description' : IDL.Text,
  'rentalDurations' : IDL.Vec(RentalDuration),
  'priceRupiah' : IDL.Nat,
  'facilities' : IDL.Vec(Facility),
  'location' : IDL.Text,
  'photos' : IDL.Vec(ExternalBlob),
});
export const ListingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Text,
});
export const Time = IDL.Int;
export const Listing = IDL.Record({
  'id' : IDL.Nat,
  'status' : ListingStatus,
  'title' : IDL.Text,
  'propertyType' : PropertyType,
  'owner' : IDL.Principal,
  'createdAt' : Time,
  'description' : IDL.Text,
  'rentalDurations' : IDL.Vec(RentalDuration),
  'priceRupiah' : IDL.Nat,
  'updatedAt' : Time,
  'facilities' : IDL.Vec(Facility),
  'location' : IDL.Text,
  'photos' : IDL.Vec(ExternalBlob),
});
export const RequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Text,
});
export const DeleteRequest = IDL.Record({
  'status' : RequestStatus,
  'owner' : IDL.Principal,
  'listingId' : IDL.Nat,
  'createdAt' : Time,
  'rejectionReason' : IDL.Opt(IDL.Text),
  'reviewedAt' : IDL.Opt(Time),
});
export const EditRequest = IDL.Record({
  'status' : RequestStatus,
  'owner' : IDL.Principal,
  'listingId' : IDL.Nat,
  'createdAt' : Time,
  'rejectionReason' : IDL.Opt(IDL.Text),
  'reviewedAt' : IDL.Opt(Time),
  'editedListing' : Listing,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveListing' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'countListingsByPropertyType' : IDL.Func([], [IDL.Nat, IDL.Nat], ['query']),
  'createListing' : IDL.Func([ListingInput], [IDL.Nat], []),
  'filterListingsByLocation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'filterListingsByPriceRange' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'getAllDeleteRequests' : IDL.Func([], [IDL.Vec(DeleteRequest)], ['query']),
  'getAllEditRequests' : IDL.Func([], [IDL.Vec(EditRequest)], ['query']),
  'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getListing' : IDL.Func([IDL.Nat], [Listing], ['query']),
  'getListingFacilities' : IDL.Func([IDL.Nat], [IDL.Vec(Facility)], ['query']),
  'getListingLocations' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getListingPhotos' : IDL.Func([IDL.Nat], [IDL.Vec(ExternalBlob)], ['query']),
  'getListingStatus' : IDL.Func([IDL.Nat], [ListingStatus], ['query']),
  'getListingsByOwner' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'processDeleteRequest' : IDL.Func(
      [IDL.Nat, IDL.Bool, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'processEditRequest' : IDL.Func(
      [IDL.Nat, IDL.Bool, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchListingsByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Listing)], ['query']),
  'submitDeleteRequest' : IDL.Func([IDL.Nat], [], []),
  'submitEditRequest' : IDL.Func([IDL.Nat, Listing], [], []),
  'uploadPhoto' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PropertyType = IDL.Variant({
    'kos' : IDL.Null,
    'kontrakan' : IDL.Null,
  });
  const RentalDuration = IDL.Variant({
    'monthly' : IDL.Null,
    'yearly' : IDL.Null,
    'daily' : IDL.Null,
  });
  const Facility = IDL.Variant({
    'wifi' : IDL.Null,
    'sharedBathroom' : IDL.Null,
    'furniture' : IDL.Null,
    'parking' : IDL.Null,
    'airConditioning' : IDL.Null,
    'laundry' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ListingInput = IDL.Record({
    'title' : IDL.Text,
    'propertyType' : PropertyType,
    'description' : IDL.Text,
    'rentalDurations' : IDL.Vec(RentalDuration),
    'priceRupiah' : IDL.Nat,
    'facilities' : IDL.Vec(Facility),
    'location' : IDL.Text,
    'photos' : IDL.Vec(ExternalBlob),
  });
  const ListingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Text,
  });
  const Time = IDL.Int;
  const Listing = IDL.Record({
    'id' : IDL.Nat,
    'status' : ListingStatus,
    'title' : IDL.Text,
    'propertyType' : PropertyType,
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'description' : IDL.Text,
    'rentalDurations' : IDL.Vec(RentalDuration),
    'priceRupiah' : IDL.Nat,
    'updatedAt' : Time,
    'facilities' : IDL.Vec(Facility),
    'location' : IDL.Text,
    'photos' : IDL.Vec(ExternalBlob),
  });
  const RequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Text,
  });
  const DeleteRequest = IDL.Record({
    'status' : RequestStatus,
    'owner' : IDL.Principal,
    'listingId' : IDL.Nat,
    'createdAt' : Time,
    'rejectionReason' : IDL.Opt(IDL.Text),
    'reviewedAt' : IDL.Opt(Time),
  });
  const EditRequest = IDL.Record({
    'status' : RequestStatus,
    'owner' : IDL.Principal,
    'listingId' : IDL.Nat,
    'createdAt' : Time,
    'rejectionReason' : IDL.Opt(IDL.Text),
    'reviewedAt' : IDL.Opt(Time),
    'editedListing' : Listing,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveListing' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'countListingsByPropertyType' : IDL.Func([], [IDL.Nat, IDL.Nat], ['query']),
    'createListing' : IDL.Func([ListingInput], [IDL.Nat], []),
    'filterListingsByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'filterListingsByPriceRange' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getAllDeleteRequests' : IDL.Func([], [IDL.Vec(DeleteRequest)], ['query']),
    'getAllEditRequests' : IDL.Func([], [IDL.Vec(EditRequest)], ['query']),
    'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getListing' : IDL.Func([IDL.Nat], [Listing], ['query']),
    'getListingFacilities' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Facility)],
        ['query'],
      ),
    'getListingLocations' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getListingPhotos' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ExternalBlob)],
        ['query'],
      ),
    'getListingStatus' : IDL.Func([IDL.Nat], [ListingStatus], ['query']),
    'getListingsByOwner' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'processDeleteRequest' : IDL.Func(
        [IDL.Nat, IDL.Bool, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'processEditRequest' : IDL.Func(
        [IDL.Nat, IDL.Bool, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchListingsByTitle' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'submitDeleteRequest' : IDL.Func([IDL.Nat], [], []),
    'submitEditRequest' : IDL.Func([IDL.Nat, Listing], [], []),
    'uploadPhoto' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };