/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface EditRequest {
    status: RequestStatus;
    owner: Principal;
    listingId: bigint;
    createdAt: Time;
    rejectionReason?: string;
    reviewedAt?: Time;
    editedListing: Listing;
}
export type Time = bigint;
export type ListingStatus = {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "approved";
    approved: null;
} | {
    __kind__: "rejected";
    rejected: string;
};
export interface Listing {
    id: bigint;
    status: ListingStatus;
    title: string;
    propertyType: PropertyType;
    owner: Principal;
    createdAt: Time;
    description: string;
    rentalDurations: Array<RentalDuration>;
    priceRupiah: bigint;
    updatedAt: Time;
    facilities: Array<Facility>;
    location: string;
    photos: Array<ExternalBlob>;
}
export type RequestStatus = {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "approved";
    approved: null;
} | {
    __kind__: "rejected";
    rejected: string;
};
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ListingInput {
    title: string;
    propertyType: PropertyType;
    description: string;
    rentalDurations: Array<RentalDuration>;
    priceRupiah: bigint;
    facilities: Array<Facility>;
    location: string;
    photos: Array<ExternalBlob>;
}
export interface DeleteRequest {
    status: RequestStatus;
    owner: Principal;
    listingId: bigint;
    createdAt: Time;
    rejectionReason?: string;
    reviewedAt?: Time;
}
export interface UserProfile {
    name: string;
    role: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Facility {
    wifi = "wifi",
    sharedBathroom = "sharedBathroom",
    furniture = "furniture",
    parking = "parking",
    airConditioning = "airConditioning",
    laundry = "laundry"
}
export enum PropertyType {
    kos = "kos",
    kontrakan = "kontrakan"
}
export enum RentalDuration {
    monthly = "monthly",
    yearly = "yearly",
    daily = "daily"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveListing(listingId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    countListingsByPropertyType(): Promise<[bigint, bigint]>;
    createListing(input: ListingInput): Promise<bigint>;
    filterListingsByLocation(location: string): Promise<Array<Listing>>;
    filterListingsByPriceRange(minPrice: bigint, maxPrice: bigint): Promise<Array<Listing>>;
    getAllDeleteRequests(): Promise<Array<DeleteRequest>>;
    getAllEditRequests(): Promise<Array<EditRequest>>;
    getAllListings(): Promise<Array<Listing>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getListing(id: bigint): Promise<Listing>;
    getListingFacilities(listingId: bigint): Promise<Array<Facility>>;
    getListingLocations(): Promise<Array<string>>;
    getListingPhotos(listingId: bigint): Promise<Array<ExternalBlob>>;
    getListingStatus(listingId: bigint): Promise<ListingStatus>;
    getListingsByOwner(owner: Principal): Promise<Array<Listing>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    processDeleteRequest(listingId: bigint, approved: boolean, rejectionReason: string | null): Promise<void>;
    processEditRequest(listingId: bigint, approved: boolean, rejectionReason: string | null): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchListingsByTitle(searchTerm: string): Promise<Array<Listing>>;
    submitDeleteRequest(listingId: bigint): Promise<void>;
    submitEditRequest(listingId: bigint, editedListing: Listing): Promise<void>;
    uploadPhoto(listingId: bigint, photo: ExternalBlob): Promise<void>;
}
import type { DeleteRequest as _DeleteRequest, EditRequest as _EditRequest, ExternalBlob as _ExternalBlob, Facility as _Facility, Listing as _Listing, ListingInput as _ListingInput, ListingStatus as _ListingStatus, PropertyType as _PropertyType, RentalDuration as _RentalDuration, RequestStatus as _RequestStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveListing(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveListing(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async countListingsByPropertyType(): Promise<[bigint, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.countListingsByPropertyType();
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.countListingsByPropertyType();
            return [
                result[0],
                result[1]
            ];
        }
    }
    async createListing(arg0: ListingInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createListing(await to_candid_ListingInput_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createListing(await to_candid_ListingInput_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async filterListingsByLocation(arg0: string): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterListingsByLocation(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterListingsByLocation(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterListingsByPriceRange(arg0: bigint, arg1: bigint): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterListingsByPriceRange(arg0, arg1);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterListingsByPriceRange(arg0, arg1);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDeleteRequests(): Promise<Array<DeleteRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDeleteRequests();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDeleteRequests();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEditRequests(): Promise<Array<EditRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEditRequests();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEditRequests();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllListings();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllListings();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListing(arg0: bigint): Promise<Listing> {
        if (this.processError) {
            try {
                const result = await this.actor.getListing(arg0);
                return from_candid_Listing_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListing(arg0);
            return from_candid_Listing_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListingFacilities(arg0: bigint): Promise<Array<Facility>> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingFacilities(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingFacilities(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListingLocations(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingLocations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingLocations();
            return result;
        }
    }
    async getListingPhotos(arg0: bigint): Promise<Array<ExternalBlob>> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingPhotos(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingPhotos(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListingStatus(arg0: bigint): Promise<ListingStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingStatus(arg0);
                return from_candid_ListingStatus_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingStatus(arg0);
            return from_candid_ListingStatus_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListingsByOwner(arg0: Principal): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingsByOwner(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingsByOwner(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async processDeleteRequest(arg0: bigint, arg1: boolean, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.processDeleteRequest(arg0, arg1, to_candid_opt_n49(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processDeleteRequest(arg0, arg1, to_candid_opt_n49(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async processEditRequest(arg0: bigint, arg1: boolean, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.processEditRequest(arg0, arg1, to_candid_opt_n49(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processEditRequest(arg0, arg1, to_candid_opt_n49(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchListingsByTitle(arg0: string): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchListingsByTitle(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchListingsByTitle(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitDeleteRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDeleteRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDeleteRequest(arg0);
            return result;
        }
    }
    async submitEditRequest(arg0: bigint, arg1: Listing): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitEditRequest(arg0, await to_candid_Listing_n50(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitEditRequest(arg0, await to_candid_Listing_n50(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadPhoto(arg0: bigint, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadPhoto(arg0, await to_candid_ExternalBlob_n21(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadPhoto(arg0, await to_candid_ExternalBlob_n21(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_DeleteRequest_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeleteRequest): DeleteRequest {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
async function from_candid_EditRequest_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EditRequest): Promise<EditRequest> {
    return await from_candid_record_n45(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Facility_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Facility): Facility {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_ListingStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingStatus): ListingStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
async function from_candid_Listing_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Listing): Promise<Listing> {
    return await from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyType_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyType): PropertyType {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_RentalDuration_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RentalDuration): RentalDuration {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_RequestStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RequestStatus): RequestStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ListingStatus;
    title: string;
    propertyType: _PropertyType;
    owner: Principal;
    createdAt: _Time;
    description: string;
    rentalDurations: Array<_RentalDuration>;
    priceRupiah: bigint;
    updatedAt: _Time;
    facilities: Array<_Facility>;
    location: string;
    photos: Array<_ExternalBlob>;
}): Promise<{
    id: bigint;
    status: ListingStatus;
    title: string;
    propertyType: PropertyType;
    owner: Principal;
    createdAt: Time;
    description: string;
    rentalDurations: Array<RentalDuration>;
    priceRupiah: bigint;
    updatedAt: Time;
    facilities: Array<Facility>;
    location: string;
    photos: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        status: from_candid_ListingStatus_n25(_uploadFile, _downloadFile, value.status),
        title: value.title,
        propertyType: from_candid_PropertyType_n27(_uploadFile, _downloadFile, value.propertyType),
        owner: value.owner,
        createdAt: value.createdAt,
        description: value.description,
        rentalDurations: from_candid_vec_n29(_uploadFile, _downloadFile, value.rentalDurations),
        priceRupiah: value.priceRupiah,
        updatedAt: value.updatedAt,
        facilities: from_candid_vec_n32(_uploadFile, _downloadFile, value.facilities),
        location: value.location,
        photos: await from_candid_vec_n35(_uploadFile, _downloadFile, value.photos)
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _RequestStatus;
    owner: Principal;
    listingId: bigint;
    createdAt: _Time;
    rejectionReason: [] | [string];
    reviewedAt: [] | [_Time];
}): {
    status: RequestStatus;
    owner: Principal;
    listingId: bigint;
    createdAt: Time;
    rejectionReason?: string;
    reviewedAt?: Time;
} {
    return {
        status: from_candid_RequestStatus_n40(_uploadFile, _downloadFile, value.status),
        owner: value.owner,
        listingId: value.listingId,
        createdAt: value.createdAt,
        rejectionReason: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.rejectionReason)),
        reviewedAt: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.reviewedAt))
    };
}
async function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _RequestStatus;
    owner: Principal;
    listingId: bigint;
    createdAt: _Time;
    rejectionReason: [] | [string];
    reviewedAt: [] | [_Time];
    editedListing: _Listing;
}): Promise<{
    status: RequestStatus;
    owner: Principal;
    listingId: bigint;
    createdAt: Time;
    rejectionReason?: string;
    reviewedAt?: Time;
    editedListing: Listing;
}> {
    return {
        status: from_candid_RequestStatus_n40(_uploadFile, _downloadFile, value.status),
        owner: value.owner,
        listingId: value.listingId,
        createdAt: value.createdAt,
        rejectionReason: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.rejectionReason)),
        reviewedAt: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.reviewedAt)),
        editedListing: await from_candid_Listing_n23(_uploadFile, _downloadFile, value.editedListing)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: string;
}): {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "approved";
    approved: null;
} | {
    __kind__: "rejected";
    rejected: string;
} {
    return "pending" in value ? {
        __kind__: "pending",
        pending: value.pending
    } : "approved" in value ? {
        __kind__: "approved",
        approved: value.approved
    } : "rejected" in value ? {
        __kind__: "rejected",
        rejected: value.rejected
    } : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kos: null;
} | {
    kontrakan: null;
}): PropertyType {
    return "kos" in value ? PropertyType.kos : "kontrakan" in value ? PropertyType.kontrakan : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    monthly: null;
} | {
    yearly: null;
} | {
    daily: null;
}): RentalDuration {
    return "monthly" in value ? RentalDuration.monthly : "yearly" in value ? RentalDuration.yearly : "daily" in value ? RentalDuration.daily : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    wifi: null;
} | {
    sharedBathroom: null;
} | {
    furniture: null;
} | {
    parking: null;
} | {
    airConditioning: null;
} | {
    laundry: null;
}): Facility {
    return "wifi" in value ? Facility.wifi : "sharedBathroom" in value ? Facility.sharedBathroom : "furniture" in value ? Facility.furniture : "parking" in value ? Facility.parking : "airConditioning" in value ? Facility.airConditioning : "laundry" in value ? Facility.laundry : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Listing>): Promise<Array<Listing>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Listing_n23(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RentalDuration>): Array<RentalDuration> {
    return value.map((x)=>from_candid_RentalDuration_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Facility>): Array<Facility> {
    return value.map((x)=>from_candid_Facility_n33(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n36(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DeleteRequest>): Array<DeleteRequest> {
    return value.map((x)=>from_candid_DeleteRequest_n38(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EditRequest>): Promise<Array<EditRequest>> {
    return await Promise.all(value.map(async (x)=>await from_candid_EditRequest_n44(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Facility_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Facility): _Facility {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
async function to_candid_ListingInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingInput): Promise<_ListingInput> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_ListingStatus_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingStatus): _ListingStatus {
    return to_candid_variant_n53(_uploadFile, _downloadFile, value);
}
async function to_candid_Listing_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Listing): Promise<_Listing> {
    return await to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): _PropertyType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_RentalDuration_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RentalDuration): _RentalDuration {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    propertyType: PropertyType;
    description: string;
    rentalDurations: Array<RentalDuration>;
    priceRupiah: bigint;
    facilities: Array<Facility>;
    location: string;
    photos: Array<ExternalBlob>;
}): Promise<{
    title: string;
    propertyType: _PropertyType;
    description: string;
    rentalDurations: Array<_RentalDuration>;
    priceRupiah: bigint;
    facilities: Array<_Facility>;
    location: string;
    photos: Array<_ExternalBlob>;
}> {
    return {
        title: value.title,
        propertyType: to_candid_PropertyType_n12(_uploadFile, _downloadFile, value.propertyType),
        description: value.description,
        rentalDurations: to_candid_vec_n14(_uploadFile, _downloadFile, value.rentalDurations),
        priceRupiah: value.priceRupiah,
        facilities: to_candid_vec_n17(_uploadFile, _downloadFile, value.facilities),
        location: value.location,
        photos: await to_candid_vec_n20(_uploadFile, _downloadFile, value.photos)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: ListingStatus;
    title: string;
    propertyType: PropertyType;
    owner: Principal;
    createdAt: Time;
    description: string;
    rentalDurations: Array<RentalDuration>;
    priceRupiah: bigint;
    updatedAt: Time;
    facilities: Array<Facility>;
    location: string;
    photos: Array<ExternalBlob>;
}): Promise<{
    id: bigint;
    status: _ListingStatus;
    title: string;
    propertyType: _PropertyType;
    owner: Principal;
    createdAt: _Time;
    description: string;
    rentalDurations: Array<_RentalDuration>;
    priceRupiah: bigint;
    updatedAt: _Time;
    facilities: Array<_Facility>;
    location: string;
    photos: Array<_ExternalBlob>;
}> {
    return {
        id: value.id,
        status: to_candid_ListingStatus_n52(_uploadFile, _downloadFile, value.status),
        title: value.title,
        propertyType: to_candid_PropertyType_n12(_uploadFile, _downloadFile, value.propertyType),
        owner: value.owner,
        createdAt: value.createdAt,
        description: value.description,
        rentalDurations: to_candid_vec_n14(_uploadFile, _downloadFile, value.rentalDurations),
        priceRupiah: value.priceRupiah,
        updatedAt: value.updatedAt,
        facilities: to_candid_vec_n17(_uploadFile, _downloadFile, value.facilities),
        location: value.location,
        photos: await to_candid_vec_n20(_uploadFile, _downloadFile, value.photos)
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): {
    kos: null;
} | {
    kontrakan: null;
} {
    return value == PropertyType.kos ? {
        kos: null
    } : value == PropertyType.kontrakan ? {
        kontrakan: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RentalDuration): {
    monthly: null;
} | {
    yearly: null;
} | {
    daily: null;
} {
    return value == RentalDuration.monthly ? {
        monthly: null
    } : value == RentalDuration.yearly ? {
        yearly: null
    } : value == RentalDuration.daily ? {
        daily: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Facility): {
    wifi: null;
} | {
    sharedBathroom: null;
} | {
    furniture: null;
} | {
    parking: null;
} | {
    airConditioning: null;
} | {
    laundry: null;
} {
    return value == Facility.wifi ? {
        wifi: null
    } : value == Facility.sharedBathroom ? {
        sharedBathroom: null
    } : value == Facility.furniture ? {
        furniture: null
    } : value == Facility.parking ? {
        parking: null
    } : value == Facility.airConditioning ? {
        airConditioning: null
    } : value == Facility.laundry ? {
        laundry: null
    } : value;
}
function to_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "approved";
    approved: null;
} | {
    __kind__: "rejected";
    rejected: string;
}): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: string;
} {
    return value.__kind__ === "pending" ? {
        pending: value.pending
    } : value.__kind__ === "approved" ? {
        approved: value.approved
    } : value.__kind__ === "rejected" ? {
        rejected: value.rejected
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<RentalDuration>): Array<_RentalDuration> {
    return value.map((x)=>to_candid_RentalDuration_n15(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Facility>): Array<_Facility> {
    return value.map((x)=>to_candid_Facility_n18(_uploadFile, _downloadFile, x));
}
async function to_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n21(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
